parse_job_description_task:
  description: >
    Thoroughly analyze the provided Job Description PDF at {job_description} and extract all key information.
  expected_output: >
    Search the job description PDF at {job_description} and extract ALL information in the following structured format:

    Job Title: 
    Company: 
    Location: 
    Required Qualifications:
    Preferred Qualifications:
    Key Responsibilities:
    Required Skills:
    Preferred Skills:
    Experience Required:
    Education Requirements:
    Company Culture and Values:
    Benefits and Perks:
    Application Instructions: [If provided]
    Additional Information: [Any other relevant details not fitting above categories]

    Ensure all sections are completed with relevent information from the job description. If a section is not applicable or information is not found, explicitly state "Not specified in the job description."

parse_resume_task:
  description: >
    Thoroughly analyze the provided Resumes PDF at {resumes} and extract all key information of candidate.
  expected_output: >
    Search the resumes PDF at {resumes} and extract ALL information of candidate in the following structured format:

    Full Name:
    Contact Information:
    Education:
    Work Experience:
    Skills:
    Projects:
    Certifications:
    Languages:
    Achievements/Awards:
    Additional Information: 

    Ensure all sections are completed with relevant information from resume, If a section is not applicable or information is not found, explicitly state "Not provided in the resume."


summarize_information_task:
  description: >
    Create a concise summary highlighting key information of given candidate's resume.

    Candidate Resume: {resumes}
  expected_output: >
    Using the parsed resume data, create a summary of candidate in the following format:

    Candidate: [Full Name]

    Email: [Email]

    Summary:
    [First Name] is a [key descriptor, e.g., "seasoned software engineer" or "recent graduate in marketing"] with [X] years of experience in [key industry/field]. Their educational background includes [highest degree] in [field of study] from [institution]. [He/She] has demonstrated expertise in [2-3 key skills relevant to the job description]. Notable achievements include [1-2 significant accomplishments or projects]. [First Name]'s experience at [most relevant company] involved [brief description of responsibilities most aligned with the job description].

    Key Qualifications:
    - [Qualification 1 relevant to the job]
    - [Qualification 2 relevant to the job]
    - [Qualification 3 relevant to the job]

    Technical Skills: [List of relevant technical skills]

    Potential Value-add: [Brief statement on how the candidate's background could benefit the company]

    Ensure the summaries capture the most relevant information for the hiring process, tailored to the job description requirements.

    Present the summaries in a clear, structured format with Highlighting Headers, ensuring all sections are completed.

  

perform_fitment_analysis_task:
  description: >
    Perform a detailed fitment analysis by comparing resume summaries with the job description given below.
    Job Description: {job_description}
    Highlight strengths, weaknesses, risk areas, and questions to ask.
  expected_output: >
    Using the job description and candidate summary, perform a detailed fitment analysis of candidate:

    Candidate: [Full Name]

    Fitment Score: [1-10, where 10 is a perfect fit]

    Strengths:
    1. [Strength 1 that aligns with job requirements]
    2. [Strength 2 that aligns with job requirements]
    3. [Strength 3 that aligns with job requirements]
    4. [Strength 4 that aligns with job requirements]
    5. [Strength 5 that aligns with job requirements]

    Weaknesses/Gaps:
    1. [Weakness or gap 1 in relation to job requirements]
    2. [Weakness or gap 2 in relation to job requirements]
    3. [Weakness or gap 3 in relation to job requirements]

    Potential Risks:
    - [Risk 1, e.g., overqualification, frequent job changes]
    - [Risk 2]
    - [Risk 3]

    Questions to Ask:
    1. [Specific question to address gap or verify strength 1]
    2. [Specific question to address gap or verify strength 2]
    3. [Specific question to address gap or verify strength 3]
    4. [Specific question to address gap or verify strength 4]
    5. [Specific question to address gap or verify strength 5]

    Overall Recommendation: [Brief statement on whether to proceed with an interview and why]

    Present the analysis in a clear, structured format with Highlighting Headers, ensuring all sections are completed.
 
